In [12]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
from sklearn.linear_model import LogisticRegression, RidgeClassifier
# from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [17]:
X_train = pd.read_csv("./data/X_train.csv")
X_test = pd.read_csv("./data/X_test.csv")
y_train =  pd.read_csv("./data/y_train.csv")
y_test = pd.read_csv("./data/y_test.csv")

y_test.isFraud.value_counts()

0    36086
1      124
Name: isFraud, dtype: int64

In [18]:
model = RandomForestClassifier()
model.fit(X_train, y_train['isFraud'])

RandomForestClassifier()

In [19]:
# Make predictions on the testing data
y_pred = model.predict(X_test)
print(y_pred)

# Generate the confusion matrix
cm = confusion_matrix(y_test['isFraud'], y_pred)

# Calculate precision, recall, and accuracy
precision = precision_score(y_test['isFraud'], y_pred, average='binary')  # Adjust 'binary' if you have multi-class classification
recall = recall_score(y_test['isFraud'], y_pred, average='binary')  # Adjust 'binary' if you have multi-class classification
accuracy = accuracy_score(y_test['isFraud'], y_pred)
f1 = f1_score(y_test['isFraud'], y_pred, average='binary')  # Adjust 'binary' if you have multi-class classification


# Print the confusion matrix and the calculated metrics
def runCM(cm, precision, recall, accuracy, f1):
    print("Confusion Matrix:")
    print(cm)
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"Accuracy: {accuracy}")
    print(f"F1 Score: {f1}")

runCM(cm, precision, recall, accuracy, f1)

[0 0 0 ... 0 0 0]
Confusion Matrix:
[[36084     2]
 [   41    83]]
Precision: 0.9764705882352941
Recall: 0.6693548387096774
Accuracy: 0.9988124827395747
F1 Score: 0.7942583732057417


# Additional Testing on Entire Dataset

In [35]:
dataSet =  pd.read_csv("./data/data.csv")
dataSet

Unnamed: 0    amount       cityPop  unixTime  merchLatitude  \
0                0  0.000032  4.143563e-05  0.000000       0.440700   
1                1  0.000021  4.925612e-06  0.000000       0.390349   
2                2  0.000178  2.080114e-06  0.000002       0.420541   
3                3  0.000074  1.871486e-05  0.000002       0.509176   
4                4  0.001002  1.188196e-05  0.000008       0.423723   
...            ...       ...           ...       ...            ...   
181817      181817  0.000566  2.660448e-04  0.999998       0.412495   
181818      181818  0.000058  7.662253e-03  0.999998       0.305187   
181819      181819  0.000359  6.172446e-07  1.000000       0.449861   
181820      181820  0.000092  5.865985e-04  1.000000       0.277880   
181821      181821  0.000069  6.354534e-05  1.000000       0.237712   

        merchLongitude     age  category_gas_transport  category_grocery_pos  \
0             0.772111  0.7375                       0                     0   
1             0.842510  0.9750                       0                     0   
2             0.448314  0.6250                       0                     0   
3             0.725492  0.5000                       0                     0   
4             0.885317  0.4875                       0                     1   
...                ...     ...                     ...                   ...   
181817        0.892959  0.6750                       0                     0   
181818        0.496819  0.5625                       0                     0   
181819        0.599924  0.3750                       0                     0   
181820        0.694989  0.2125                       0                     0   
181821        0.845189  0.0875                       0                     0   

        category_shopping_net  distance_between  isFraud  risk  
0                           0          0.572049        0     0  
1                           1          0.298690        0     0  
2                           0          0.823143        0     0  
3                           0          0.507048        0     0  
4                           0          0.358400        0     0  
...                       ...               ...      ...   ...  
181817                      0          0.227643        0     0  
181818                      0          0.419812        0     1  
181819                      0          0.627880        0     0  
181820                      0          0.500155        0     0  
181821                      0          0.751359        0     0  

[181822 rows x 13 columns]

In [46]:
import numpy as np
y_prob = model.predict_proba(dataSet.drop(["isFraud", "risk"], axis=1))[:, 1]

# Use np.where to set different thresholds based on the 'risk' column
thresholds = np.where(dataSet['risk'] == 1, 0.4, 0.67)
y_pred2 = y_prob >= thresholds

# Generate the confusion matrix
cm = confusion_matrix(dataSet["isFraud"], y_pred2)

# Calculate precision, recall, and accuracy
precision = precision_score(dataSet["isFraud"], y_pred2, average='binary')  # Adjust 'binary' if you have multi-class classification
recall = recall_score(dataSet["isFraud"], y_pred2, average='binary')  # Adjust 'binary' if you have multi-class classification
accuracy = accuracy_score(dataSet["isFraud"], y_pred2)
f1 = f1_score(dataSet["isFraud"], y_pred2, average='binary')  # Adjust 'binary' if you have multi-class classification


# Print the confusion matrix and the calculated metrics
def runCM(cm, precision, recall, accuracy, f1):
    print("Confusion Matrix:")
    print(cm)
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"Accuracy: {accuracy}")
    print(f"F1 Score: {f1}")

runCM(cm, precision, recall, accuracy, f1)

Confusion Matrix:
[[180485      1]
 [   490    846]]
Precision: 0.9988193624557261
Recall: 0.6332335329341318
Accuracy: 0.9972995567093091
F1 Score: 0.7750801649106733


In [50]:

dfNew = pd.read_csv('data/data.csv')
dfNew

Unnamed: 0    amount   cityPop  unixTime  merchLatitude  merchLongitude  \
0              0  0.160662  0.000039  0.030577       0.570467        0.688879   
1              1  0.031883  0.001048  0.918571       0.562831        0.756507   
2              2  0.002516  0.138095  0.248599       0.476093        0.723469   
3              3  0.002141  0.000135  0.922283       0.579759        0.517627   
4              4  0.195016  0.005501  0.487544       0.290348        0.616094   
...          ...       ...       ...       ...            ...             ...   
2246        2246  0.011937  0.000431  0.295786       0.507805        0.711537   
2247        2247  0.002690  0.001095  0.254998       0.243002        0.684482   
2248        2248  0.015527  0.003642  0.357673       0.269061        0.703152   
2249        2249  0.014807  0.000322  0.991882       0.494187        0.901244   
2250        2250  0.025408  0.000445  0.878344       0.414505        0.918566   

         age  category_gas_transport  category_grocery_pos  \
0     0.4375                       0                     0   
1     0.3625                       0                     0   
2     0.6125                       0                     0   
3     0.1125                       0                     0   
4     0.0500                       0                     0   
...      ...                     ...                   ...   
2246  0.6250                       1                     0   
2247  0.3625                       1                     0   
2248  0.1500                       0                     0   
2249  0.1625                       1                     0   
2250  0.2500                       0                     0   

      category_shopping_net  distance_between  risk  
0                         0          0.516566     0  
1                         0          0.570053     0  
2                         0          0.356844     0  
3                         0          0.639073     1  
4                         0          0.636571     0  
...                     ...               ...   ...  
2246                      0          0.826156     0  
2247                      0          0.570021     0  
2248                      0          0.702138     0  
2249                      0          0.192124     0  
2250                      0          0.269236     0  

[2251 rows x 12 columns]

In [55]:
y_prob = model.predict(dfNew.drop(["risk"], axis=1))


In [57]:
y_prob.shape

(2251,)

In [58]:
finalTest = pd.read_csv("dataquest_fraud_test.csv")   
finalTest['isFraud'] = y_prob

In [59]:
finalTest

transDate        creditCardNum  \
0     2020-06-27 19:47     3573390000000000   
1      2020-12-16 6:29     3579200000000000   
2     2020-08-08 22:02      343819000000000   
3     2020-12-16 23:41  4292900000000000000   
4      2020-09-24 1:14        4427810000000   
...                ...                  ...   
2246   2020-08-18 0:41        4623560000000   
2247   2020-08-10 3:41       30238800000000   
2248  2020-08-29 23:27     4908850000000000   
2249  2020-12-30 10:11       30407700000000   
2250  2020-12-08 12:05      345934000000000   

                                 business       category  amount  firstName  \
0                       fraud_Volkman Ltd       misc_net  667.17  Stephanie   
1                  fraud_Pfeffer and Sons   shopping_pos  132.40      Tyler   
2                       fraud_Kovacek Ltd         travel   10.45     Shelby   
3                    fraud_Lemke and Sons         travel    8.89    Jeffrey   
4                       fraud_Kerluke Inc       misc_net  809.83   Michelle   
...                                   ...            ...     ...        ...   
2246  fraud_Robel, Cummerata and Prosacco  gas_transport   49.57    Vincent   
2247                fraud_Cummerata-Jones  gas_transport   11.17   Danielle   
2248                fraud_Crooks and Sons  personal_care   64.48     Lauren   
2249                      fraud_Emard Inc  gas_transport   61.49   Danielle   
2250              fraud_Cruickshank-Mills  entertainment  105.51      Carol   

       lastName gender                         street         city  ...  \
0        Murphy      F                526 Stacy Walks      Barnard  ...   
1         Small      M                047 Kevin Haven         Boyd  ...   
2        Cannon      F      1535 Ryan Burgs Suite 919   Des Moines  ...   
3         Smith      M           135 Joseph Mountains         Sula  ...   
4     Rodriguez      F  1742 Brandon Squares Apt. 461      Ruidoso  ...   
...         ...    ...                            ...          ...  ...   
2246     Waller      M      9379 Vanessa Run Apt. 400    Lohrville  ...   
2247         Yu      F     5395 Colon Burgs Suite 037       Thrall  ...   
2248     Torres      F              03030 White Lakes    Grandview  ...   
2249      Evans      F     76752 David Lodge Apt. 064    Breesport  ...   
2250     Dillon      F              27479 Reeves Dale  Whaleyville  ...   

     latitude  longitude  cityPop                         job  dateOfBirth  \
0     45.7205   -98.5534       63           Systems developer   1969-10-30   
1     44.9437   -91.0294     1690                  IT trainer   1975-12-24   
2     41.5855   -93.6719   222785          Wellsite geologist   1956-01-24   
3     45.8433  -113.8748      218    Therapist, horticultural   1995-08-16   
4     33.3305  -105.6933     8874        Licensed conveyancer   2000-08-16   
...       ...        ...      ...                         ...          ...   
2246  42.2619   -94.5566      695               Administrator   1954-07-15   
2247  30.5920   -97.2893     1766                   Press sub   1976-01-02   
2248  32.2779   -97.2351     5875   Radiographer, therapeutic   1992-07-24   
2249  42.1939   -76.7361      520             Psychotherapist   1991-10-13   
2250  38.4121   -75.2811      718  Regulatory affairs officer   1985-03-19   

                              transNum    unixTime merchLatitude  \
0     276495f58de3af46843647fdd00843eb  1372362479     46.040300   
1     0bd7e2199cc5dbe847d90f1ca1d94974  1387175381     45.680527   
2     873e753bf1a897daf144b2fe9b039fd2  1375999332     41.593729   
3     fdfa039f3d2678522f57003bf1c38a7f  1387237267     46.478129   
4     f442042f8f14ec7cd9d5fddece9b75b2  1379985277     32.842035   
...                                ...         ...           ...   
2246  7641e8acbcbc7ead2c5e19c8a65a9596  1376786463     43.087884   
2247  17afa1e98c9f427f4c4c7bfc0654f248  1376106091     30.611255   
2248  35c8b62ff6319568e12288d5fe50356a  137781883

In [60]:
finalTest.to_csv('dataquest_fraud_test.csv', index=False)